name: Converter fontes.txt em canais_temp.json

on:
  push:
    paths:
      - 'fontes.txt'
  workflow_dispatch:

jobs:
  converter:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          python -m playwright install

      - name: Rodar captura_links.py
        run: python captura_links.py

      - name: Commit canais_temp.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git fetch origin
          git reset --hard origin/main
          git add canais_temp.json
          git commit -m "Atualização automática do canais_temp.json" || echo "Sem alterações"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
