name: Gerar lista.m3u

on:
  push:
    paths:
      - 'canais.json'
  workflow_dispatch:

jobs:
  gerar-m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Rodar gerar_m3u.py
      run: python gerar_m3u.py

    - name: Commit lista.m3u
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git fetch origin
        git reset --hard origin/main
        git add lista.m3u
        git commit -m "Atualização automática da lista.m3u"
        git push
