name: Merge canais_temp.json com canais.json

on:
  push:
    paths:
      - 'canais_temp.json'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Rodar merge_canais_json.py
      run: python merge_canais_json.py

    - name: Commit canais.json
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git fetch origin
        git reset --hard origin/main
        git add canais.json
        git commit -m "Atualização automática do canais.json"
        git push
